# Site settings
title: Matthias Weiss
twitter_username: matthiasweiss
name: Matthias Weiss

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/weissm
 - title: LinkedIn
   url: https://www.linkedin.com/in/matthiasweiss/

#Any buzzword skills you want to include
skills:
